### ISSUE TITLE
Example with codegen.yml - MercuriusContext

### ISSUE THREAD

**Issue by stolinski** [mercurius-js/mercurius-typescript#9]
We're using codegen.yml for our generation via 

```
overwrite: true
schema: './src/**/**/*.graphql'
documents: '../ui/src/**/*.graphql'
generates:
  ./src/types/generated.ts:
    config:
      defaultMapper: any
      contextType: ./customTypes#Context
    plugins:
      - typescript
      - typescript-operations
      - typescript-resolvers
      - mercurius-codegen
```

All is working well, except for MercuriusContext not getting our custom context types. I see how context type is created in the programmic examples however I can't figure out how to generate correctly with this setup. 

With normal codegen, it's done via

```
    config:
      defaultMapper: any
      contextType: ./customTypes#Context
```

I've poked around the repo, but didn't see anything that would be the same.
